DROP TABLE PerformanceReview CASCADE CONSTRAINTS;

DROP TABLE Leave CASCADE CONSTRAINTS;

DROP TABLE Position CASCADE CONSTRAINTS;

DROP TABLE MedicalSpecialty CASCADE CONSTRAINTS;

DROP TABLE Department CASCADE CONSTRAINTS;

DROP TABLE Employee CASCADE CONSTRAINTS;
